### ISSUE TITLE
telekom sperre?

### ISSUE THREAD

**Issue by uragan1987** [Haxe18/telekom_fon_connect#4]
Hallo

hatte heute versucht den script bei mir auf RPI3 zu starten.
Es klappte, jedoch nicht lange.
nach ca 5min war die verbindung verloren und kein login mehr möglich
mit dem smartphone gings auch nicht.
heißt, das telekom ein sperre drin hat bei vielen usern gleichzeitig oder muss man etwas beachten?

Gruß
Andi

PS: top script, danke fürs share

**Comment by uragan1987** [comment]
Fehler beim Login: 815
Was hat den das zu bedeuten?

**Comment by Haxe18** [comment]
Hi,

das Script funktioniert also noch und ein Login klappt ?
Dann kann ich #3 quasi schließen :)

Dein Fehler 815 kommt nicht von meinem Script und scheint ein Doppel Login Fehler zu sein:
https://telekomhilft.telekom.de/t5/Telefonie-Internet/Telekom-fon-Login-Nicht-moeglich/td-p/4202369
Vermutlich ist dieser Fehler dann tatsächlich eine Sperre für einen doppelten Login.

Wenn du mehrere Geräte via Hotspot ins Netz lassen möchtest, wäre eine Einrichtung deines Raspi's als NAT-Gateway die Lösung 😉
