### ISSUE TITLE
include NAT setup

### ISSUE THREAD

**Issue by hackrid** [Haxe18/telekom_fon_connect#5]
Hi,

what about including a NAT configuration into the project?

thanks for your effort!

**Comment by Haxe18** [comment]
Sorry, but a nat configuration has nothing to do with the project.
This was my purpose to create and use the script, but you can also use it on you personal computer to auto connect to the wifi, not needing any nat.

Google for it and you will find many tutorials how to nat and also how to create a wlan repeater with the detailed explained differences like wifi 2.4GHZ and 5GHZ autochannel and so on described.

In my case i used dnsmasq with iptables and hostapd.
