### ISSUE TITLE
Login with FON credentials

### ISSUE THREAD

**Issue by hackrid** [Haxe18/telekom_fon_connect#6]
Hi,

is it possible to use the script with FON credentials as well?

br

**Comment by Haxe18** [comment]
Hi,

don't know because i only own a telekom account and no fon account (as explained in Readme.md: **ONLY** Telekom customers @ **Telekom_FON** named Hotspot.).
Give it a try and tell me if it works, but i don't think so.

**Comment by Neokeymann** [comment]
@hackrid Did you test it? It works ?

**Comment by Neokeymann** [comment]
@Haxe18 Hi ich habe Fon Login Daten , habe dein Script aber noch nicht getestet . Es müsste doch aber auch möglich sein das es damit auch geht.

**Comment by Haxe18** [comment]
Hi @Neokeymann ,

wie gesagt ich habe nur einen Telekom Account (im Handy Vertrag inklusive) und keinen Fon Account.
Da der telekom_api_endpoint (siehe telekom_fon_connect.conf) explizit eine Telekom Url und keine FON ist, vermute ich, mit Fon Accounts funktioniert mein Script nicht, da anderer Endpoint und anderer Login Mechanismus.
Aber so lange es keiner testet, werden wir es nie erfahren ;)

Ich mache hier mal zu, wenn es geht mit FON Login gerne ein neues Issue aufmachen und mir mitteilen.
